name: Greengear
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47427
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9605130448471755
  lightness: 0.10417871014215052
  saturation: 0.48095764475874603
  rhythmicContrast: 0.6839396122377366
purpose: []
